before_install:
- mkdir -p /home/travis/.hab/cache/keys
- mkdir build_logs
- cp chrisortman-20160618040827.pub /home/travis/.hab/cache/keys
- openssl aes-256-cbc -K $encrypted_2c143b8c5811_key -iv $encrypted_2c143b8c5811_iv
  -in chrisortman-20160618040827.sig.key.enc -out ~/.hab/cache/keys/chrisortman-20160618040827.sig.key
  -d
install:
- curl https://raw.githubusercontent.com/habitat-sh/habitat/master/components/hab/install.sh | sudo bash
script:
- hab studio -r /hab/studio/sparc build -R habitat/sparc-request-base | tee build_logs/sparc_request_base.log
- travis_wait hab pkg upload results/*.hart
after_success:
- cat build_logs/sparc_request_base.log
after_failure:
- cat build_logs/sparc_request_base.log
env:
  global:
  - HAB_ORIGIN=chrisortman
  - HAB_ORIGIN_KEYS=chrisortman
  - HAB_NONINTERACTIVE=true
  - HAB_LICENSE=accept
