default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  variables:
    sql_mode: TRADITIONAL

production:
  <<: *default
  database: {{cfg.fullfillment.database_name}}
  username: {{cfg.fulfillment.database_username}}
  password: {{cfg.fulfillment.database_password}}
  host: {{cfg.fulfillment.database_host}}
  port: {{cfg.fulfillment.database_port}}
